[tool.poetry]
name = "integration-testing"
version = "0.1.0"
license = "MPL-2.0"
description = "Integration testing for Yari"
authors = ["MDN Devs <mdn-dev@mozilla.com>"]
repository = "https://github.com/mdn/yari"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
pytest = "^7.1.3"
pytest-base-url = "^2.0.0"
pytest-rerunfailures = "^10.2"
requests = "^2.28.1"
pyquery = "^1.4.3"
braceexpand = "^0.1.7"

[tool.poetry.dev-dependencies]
black = "^22.10"
flake8 = "^5.0.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
