[tool.poetry]
name = "deployer"
version = "0.1.0"
license = "MPL-2.0"
description = "Upload the files that Yari built"
authors = ["MDN Devs <mdn-dev@mozilla.com>"]
repository = "https://github.com/mdn/yari"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
click = "^8.1.3"
boto3 = "^1.24.89"
python-decouple = "^3.6"
requests = {extras = ["security"], version = "^2.28.1"}
elasticsearch-dsl = "^7.4.0"
selectolax = "^0.3.11"
PyGithub = "^1.55"
unidiff = "^0.7.4"

[tool.poetry.dev-dependencies]
black = "^22.8"
flake8 = "^5.0.4"
pytest = "^7.1.3"

[tool.poetry.scripts]
deployer = "deployer.main:cli"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
