[tool.poetry]
name = "deployer"
version = "0.1.0"
license = "MPL-2.0"
description = "Upload the files that Yari built"
authors = ["MDN Devs <mdn-dev@mozilla.com>"]
repository = "https://github.com/mdn/yari"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
click = "^8.0.3"
boto3 = "^1.20.24"
python-decouple = "^3.5"
requests = {extras = ["security"], version = "^2.26.0"}
elasticsearch-dsl = "^7.4.0"
selectolax = "^0.3.6"
PyGithub = "^1.55"
unidiff = "^0.7.0"

[tool.poetry.dev-dependencies]
black = "^21.12b0"
flake8 = "^4.0.1"
pytest = "^6.2.5"

[tool.poetry.scripts]
deployer = "deployer.main:cli"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

