name: Compare bundle size

on:
  pull_request:

# No GITHUB_TOKEN permissions, as we only use it to increase API limit.
permissions: {}

jobs:
  # Build current and upload stats.json
  build-head:
    if: github.event.pull_request.head.repo.full_name == github.repository
    name: "Build head"
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (head)
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: yarn

      - name: Install all yarn packages
        run: yarn --frozen-lockfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: yarn build:client
        env:
          ANALYZE_BUNDLE_PR: true

      - name: Upload stats.json
        uses: actions/upload-artifact@v4
        with:
          name: head-stats
          path: ./client/build/stats.json

  # Build base for comparison and upload stats.json
  build-base:
    if: github.event.pull_request.head.repo.full_name == github.repository
    name: "Build base"
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (base)
        uses: actions/checkout@v5
        with:
          ref: ${{ github.base_ref }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: yarn

      - name: Install all yarn packages
        run: yarn --frozen-lockfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: yarn build:client
        env:
          ANALYZE_BUNDLE_PR: true

      - name: Upload stats.json
        uses: actions/upload-artifact@v4
        with:
          name: base-stats
          path: ./client/build/stats.json

  # run the action against the stats.json files
  compare:
    if: github.event.pull_request.head.repo.full_name == github.repository
    name: "Compare base & head bundle sizes"
    runs-on: ubuntu-latest
    needs: [build-base, build-head]
    permissions:
      pull-requests: write
    steps:
      - uses: actions/download-artifact@v5
      - uses: github/webpack-bundlesize-compare-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          current-stats-json-path: ./head-stats/stats.json
          base-stats-json-path: ./base-stats/stats.json
